### ISSUE TITLE
Accepting a game

### ISSUE THREAD

**Issue by eddy5641** [loldevs/leaguespec#11]
Service Name: lcdsGameInvitationService
Method Name: accept
String InvitationId (looks like INVID158928100)
Returns: LobbyStatus

**Comment by Divi** [comment]
Hello @eddy5641,

Thanks for this missing method. The string `invitationId` is the method parameter ?

**Comment by eddy5641** [comment]
Yes invitationId is the Parameter
also declining a game is the same except the method name is decline

**Comment by Divi** [comment]
Thanks @eddy5641, added :+1:
