### ISSUE TITLE
Riot releases new data, need to compare with our keyframe/chunk specs

### ISSUE THREAD

**Issue by Divi** [loldevs/leaguespec#12]
See :
- https://acs.leagueoflegends.com/v1/stats/game/NA1/1414415714/
- https://acs.leagueoflegends.com/v1/stats/game/NA1/1414415714/timeline

We can compare data with the last keyframe of the game and found some of unknown parts.

More information here : https://github.com/loldevs/leaguespec/wiki/Lobby-REST-Service

**Comment by jaagupkymmel** [comment]
Can those be queryed before the game ends?

**Comment by Divi** [comment]
Like I said in the wiki after the `gameId` parameter : no

**Comment by themasch** [comment]
Wow, this is huge. We should compare those results and check if we can test parsers against this & use this data (for example coords) to find out more information in keyframes. nice find!

**Comment by Divi** [comment]
Here we go, first review, I put it here because I'm not sure about data, I need more verifications with more keyframes :

---

A3 00 28 01
00 00 45 00 
28 01 00 00  // 296
06 00 00 00  // 6 - assists
00 00 00 00  // 0
07 00 00 00  // 7 - kills
0F 00 00 00  // 15 - `killing spree ?`
01 00 00 00  // 1 - `doubleKills ?`
00 00 00 00  // 0 - `tripleKills ?`
00 00 00 00  // 0 - `quadraKills ?`
00 00 00 00  // 0 - `pentaKills ?`
00 00 00 00  // 0 - `unrealKills ?`
F8 26 1C 46  // 9993.742188 - total gold earned
00 6C 02 46  // 8347 - gold spent
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00
00 00 00 00  // 0
1F 00 00 00  // 31
03 00 00 00  // 3
93 85 30 43  // 176.521774 - `largestCriticalStrike ?`
03 00 00 00  // 3 - `largestKillingSpree ?`
02 00 00 00  // 2 - `largestMultiKill ?`
00 00 00 00  // 0
CB 0A 26 44  // 664.168640 - `longestTimeSpentLiving ?`
08 A0 6C 45  // 3786.001953 - `magicDamageDealt ?`
C4 CC 7F 43  // 255.799866 - `magicDamageDealtToChampions ?`
CC 13 E5 45  // 7330.474609 - `magicalDamageTaken ?`
17 00 00 00  // 23 - minions
00 00
4B 00 00 00  // 75 - `neutralMinionsKilled ?`
05 00 00 00  // 5 - `neutralMinionsKilledEnemyJungle ?`
46 00 00 00  // 70 - `neutralMinionsKilledTeamJungle ?`
04 00 00 00  // 4 - deaths
00 00 00 00  // 0
8B AA AF 47  // 89941.085938 - `physicalDamageDealt ?`
48 23 42 46  // 12424.820312 - `totalDamageDealtToChampions ?`
CF 45 0A 46  // 8849.452148 - `physicalDamageTaken ?`
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00
3E 00 00 00  // 62
00 00 00 00  // 0
44 00 00 00  // 68
09 00 00 00  // 9
04 00 00 00  // 4
13 00 00 00  // 13
00 00 00 00  // 0
64 00 00 00  // 100 - `teamId ?`
00 00 00 00  00 00 00 00  00 00 00 00
7B 7F D4 47  // 108798.960938 - `totalDamageDealt ?`
CB 6F 5D 46  // 14171.948242 - `totalDamageDealtToChampions ?`
EA 77 86 46  // 17211.957031 - `totalDamageTaken ?`
B1 09 00 00  // 2481 - `totalHeal ?`
CD 04 BE 43  // 380.037506 - `totalTimeCrowdControlDealt ?`
18 4B 00 43  // 128.293335 - `totalTimeSpentDead ?`
01 00 00 00  // 1 - `visionWardsBoughtInGame ?`
00 00 00 00  // 0 - `sightWardsBoughtInGame ?`
12 80 6B 46  // 15072.017578 - `trueDamageDealt ?`
AD 6A BA 44  // 1491.333618 - `trueDamageDealtToChampions ?`
11 01 81 44  // 1032.033325 - `trueDamageTaken ?`
00 00 00 00  // 0 - `turretKills ?`
00 00 00 00  // 0 - `inhibitorKills ?`
00 00 00 00  // 0 
00 00 00 00  // 0 - `wardsKilled ?`
07 00 00 00  // 7 - `wardsPlaced ?`
00 00 00 00  // 0 - 
00 00 00 00  // 0
00 00

---
- ? : I'm sure, 90%
- ??? : I'm not sure

It still miss some data, but it's a big improvement for now :smiley:

**Comment by themasch** [comment]
Yay, nice work @Divi. :+1:

**Comment by themasch** [comment]
Wow, I just saw that the timeline even contains kill-events like these: 

```
{
  type: "BUILDING_KILL",
  timestamp: 1822376,
  position: {
    x: 802,
    y: 4052
  },
  killerId: 7,
  assistingParticipantIds: [
    8
  ],
  teamId: 100,
  buildingType: "TOWER_BUILDING",
  laneType: "TOP_LANE",
  towerType: "BASE_TURRET"
},
{
  type: "CHAMPION_KILL",
  timestamp: 1830787,
  position: {
    x: 5889,
    y: 755
  },
  killerId: 2,
  victimId: 9,
  assistingParticipantIds: [ ]
}
```

This is huge, maybe we can even use this for information in chunks. RIOT I <3 U

**Comment by Divi** [comment]
How about to replace the current "unknown data" part with an array, like this :

| Offset | Hex | Length | Value | Description |
| --- | --- | --- | --- | --- |
| 0x00 | 01 00 00 00 | 0x04 | 1 | Foo bar |
| 0x04 | 09 00 | 0x02 | 9 | Bar foo |

I think it's most readable.

**Comment by jaagupkymmel** [comment]
I think that's a great idea.

**Comment by Divi** [comment]
I'll replace the part this week-end if nobody is against this idea.

**Comment by themasch** [comment]
:+1:

**Comment by Zero3** [comment]
:+1:

**Comment by lukegb** [comment]
:+1: Sounds good to me!

**Comment by Divi** [comment]
Wiki updated :+1:
