### ISSUE TITLE
Seems I'm not able to join a Custom Lobby Chat :S

### ISSUE THREAD

**Issue by ecklf** [loldevs/leaguespec#18]
Been proramming a bit for a LoL XMPP Bot and found your wiki here :+1: 
https://github.com/loldevs/leaguespec/wiki/XMPP
Can I get those Invitation ID's with the raw client or how did you guys find out?

**Comment by Divi** [comment]
See #9 for more information about chat name (ID) generation, if it's what you're talking about.

**Comment by ecklf** [comment]
Yeah I kinda saw how that works now (sry for that fast edits). I just wonder how you got the Invitation ID Itself.
