### ISSUE TITLE
Error in documented keyframe player segment header

### ISSUE THREAD

**Issue by Zero3** [loldevs/leaguespec#19]
https://github.com/loldevs/leaguespec/wiki/Keyframe-Player-Segment claims the following:

---

There are many possible sequences for the beginning of the header.

```
!! !! C3 !! 11 00 [00 00 00]
```
- **Marker #1** : can be `0x93` or `0xB3`  
- **Marker #2** : can be `0x00` or `0x01`  
- **Marker #3** : can be `0x4B` or `0x4C`

**Note:** when the #1 marker is `0x93`, there is three more `0x00` at the end, example : `93 01 C3 4B 11 00 00 00 00`

---

The 0x11 as byte 5 appears to be wrong. I have a keyframe which starts the first player segment header at the following 16 bytes:

0xb3 0x0 0xc3 0x4b 0x0 0x19 0x0 0x0 0x40 0x8 0x0 0x0 0x0 0x40 0x1b 0x1

The 0x11 was introduced in [this edit](https://github.com/loldevs/leaguespec/wiki/Keyframe-Player-Segment/_compare/4356f8f3c167bc7e30aa981aa835e89e8e94e704%5E...4356f8f3c167bc7e30aa981aa835e89e8e94e704). is the 0x11 a mistake @Divi?

**Comment by Divi** [comment]
Yes sorry, maybe a wrong copy/paste. I'll edit this, thanks :+1: 
I also found that the first marker can be `0xF4` or `0x44`, but it appears in only 1 per 100 games and for only one player, I don't know why.
