### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by themasch** [loldevs/leaguespec#2]
We should pick a good license for this stuff. 

Possible picks could be the
- [GNU FDL](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) 
- [CC BY-SA](https://creativecommons.org/licenses/)
- [PDL](http://www.openoffice.org/licenses/PDL.html)

Are there any other noteable?

**ATTENTION**: This should most likly be done AFTER #3 .

**Comment by lukegb** [comment]
I suggest we go Wikipedia-style and dual-license GFDL/CC BY-SA. Failing that, just straight CC BY-SA suits me fine.

**Comment by jaagupkymmel** [comment]
CC-BY-SA seems to be the best one.

**Comment by Divi** [comment]
@jaagupkymmel +1.

**Comment by themasch** [comment]
Okay, so we'll pick CC-BY-SA? 
@lukegb can you please explain the reasoning behind dual-license? Honestly, I never understoot that concept :(

**Comment by tyscorp** [comment]
I'm fine with CC BY-SA.

**Comment by lukegb** [comment]
CC BY-SA suits me. Do it! :+1:
