### ISSUE TITLE
Another error in documented keyframe player segment header

### ISSUE THREAD

**Issue by Zero3** [loldevs/leaguespec#20]
https://github.com/loldevs/leaguespec/wiki/Keyframe-Player-Segment claims the following:

---

[...] followed by the rest of the header. (the structure of this is consistent)

```
++ ++ ++ 40                 // Entity ID
!! 00 00 00                 // Player number
40 00 XX 00
XX FF XX 00
00 00
```

---

The 0x00 as byte 5 after the player number (just after the 0x40) appears to be wrong. I have a keyframe containing the following 13 bytes after the player number:

0x00 0x00 0x00 0x40 **0x1B** 0x01 0x00 0xA4 0xFF 0x02 0x00 0x00 0x00

**Comment by themasch** [comment]
yeah, most of this is just guessed or "not seen something else, so this might be it". Go ahead and change it  if you've seen other variants ;)

**Comment by Divi** [comment]
Like said @themasch, most of these bytes are not static. See #15.
I'll update the wiki with dynamic and static parts when I have more time (maybe at the end of the next week).

**Comment by Zero3** [comment]
Alright, I blanked out the relevant byte with 'XX' in the specs :).

**Comment by Divi** [comment]
Thanks !
