### ISSUE TITLE
Summoner Name charset not documented in keyframe specification

### ISSUE THREAD

**Issue by Zero3** [loldevs/leaguespec#21]
https://github.com/loldevs/leaguespec/wiki/Keyframe-Player-Segment#summoner-name should specify a charset.

**Comment by Zero3** [comment]
It appears to be some Latin1 variant. (EDIT: But what about localized names on non-western servers?)

**Comment by avborhanian** [comment]
Just tried using the Korean server spectate rest service, and looking at the names, it looks like the charset used is UTF-8, which would be backwards compatible with ASCII. It's probably UTF-8 throughout.

**Comment by themasch** [comment]
i'm pretty sure its UTF-8. Checked that months ago when I wrote the first docs, and I was pretty sure its UTF-8. Can't remember why I didn't wrote it down. Maybe there have been some non-utf8 chars?

**Comment by jaagupkymmel** [comment]
Seems to be UTF-8. Closing the issue for now, reopen this or open a new one if there is evidence to suggest that this is not the case.
