### ISSUE TITLE
Map rune IDs to runes

### ISSUE THREAD

**Issue by Zero3** [loldevs/leaguespec#22]
https://github.com/loldevs/leaguespec/wiki/Keyframe-Player-Segment#rune-page contains examples of rune IDs, but we need to figure out how to map these into actual runes.

**Comment by Zero3** [comment]
Parsing the first two bytes of each rune entry as an unsigned integer seems to give rune ID's matching the official API data (see http://ddragon.leagueoflegends.com/tool/euw/en_US for example). Can anyone confirm?

**Comment by Divi** [comment]
Confirmed, according to the [rune.json](http://ddragon.leagueoflegends.com/cdn/4.13.1/data/en_US/rune.json) :+1: 

I don't know if missing runes (when the player is not level 30) are transformed into padding or just deleted. In this case, the length is variable.

**Comment by Zero3** [comment]
Nice. Since the last two bytes of each entry appear to be 0x00 all the time, we can probably assume that the ID is in fact 4 bytes long, leaving room for future expansion.

**Comment by Divi** [comment]
If needed, runes are also available with the RTMP API, especially the [Spellbook service](https://github.com/loldevs/leaguespec/wiki/RTMP-Service-Methods#spellbookservice). The selected spellbook has the key `current` to `true`.

**Comment by Divi** [comment]
Added description in the keyframe page : https://github.com/loldevs/leaguespec/wiki/Keyframe-Player-Segment/_compare/75f68ed11c94b31d2e72990d6e4540124955b94b%5E...75f68ed11c94b31d2e72990d6e4540124955b94b

Can we close this ticket @Zero3 ?

**Comment by jaagupkymmel** [comment]
I don't think it's a 16-bit integer and 16-bit padding, rather a 32-bit integer.

**Comment by Divi** [comment]
Good point, I edited the wiki.

**Comment by Zero3** [comment]
Thanks @Divi !

I've created a separate issue for the open question regarding empty rune slots at #26.
