### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by jaagupkymmel** [loldevs/leaguespec#23]
Should we create a simple website for leaguespec/loldevs? Some parts of the project are going along really slowly, this could serve the purpose of making it easier for new devs to join the project.

**Comment by honux** [comment]
I don't make part on the original team, but honestly I don't see how this would improve the development.
At least for me, it seems that it will just create an unnecessary cost.

**Comment by themasch** [comment]
it could be used for additional informations and communication with the outside work. 
There are no additional costs if we use gh-pages first.

**Comment by jaagupkymmel** [comment]
We could use a github.io page, there is no need for running any server-side logic. It could just be a simple landing page that explains what we do, why we do it and how to help us out.

**Comment by themasch** [comment]
:+1:

**Comment by honux** [comment]
Then it would be awesome :p

**Comment by lukegb** [comment]
:+1: to this

Yeah - just whack up a GitHub Pages page and be done with it. It'll be great! There'll be fun, and laughter, _and cake_...

(yes, I'm still alive, just super busy right now)

Someone should make the loldevs.github.io repo.
