### ISSUE TITLE
Keyframe killing spree has moved

### ISSUE THREAD

**Issue by Divi** [loldevs/leaguespec#24]
The killing spree data (triple kill, quadra kill & penta kill) has moved, and I don't have keyframe with quadra or penta kill.

If someone has a keyframe, please share it !
The previous keyframe (before the quadra/penta) will be great.

**Comment by Divi** [comment]
I done a game with bot in 1 v 5 to make a quadra/penta. So I've only one game with a penta and two with quadra.
- Current killing spree : offset `0x60`
- Double kill (no move) : offset `0x1C`
- Triple kill : offset `0x102`, so "Sight wards bought (pink)" should be at offset `unknown`
- Quadra kill : offset `0xAE`
- Penta kill : offset `0x9A`

and bonus : "Vision wards bought (green) (`0xFE`)" become "Total unit healed"

**Comment by themasch** [comment]
You got a penta in a bot game? How did you manage to make them teamfight so you get them all on the same place? :D

**Comment by Divi** [comment]
:smile: I let them take my inhibitors and kill them in front of the nexus.
