### ISSUE TITLE
Check how empty rune slots are represented

### ISSUE THREAD

**Issue by Zero3** [loldevs/leaguespec#26]
At https://github.com/loldevs/leaguespec/wiki/Keyframe-Player-Segment#rune-page we need some specification about how empty rune slots are represented.

Maybe the respective integers are 0, maybe they are left out of the data and maybe something completely different happens. Someone needs to check and update the wiki page.

**Comment by Divi** [comment]
@Zero3 empty runes are represented by `00 00 00 00`. If player hasn't rune page (below level 20), the part is full of `00 00 00 00`.

Here a decoded keyframe example : [keyframe 1 - #1609602760 (EUW).txt](http://snk.to/f-cdhiwkhv)
- Player `Legetimniy` has no rune (level 19).
- Player `Snifflum` has a few runes (level 24)
- Player `TheMrKunKun` has full runes (level 30 & ranked)

**Comment by Zero3** [comment]
Thanks @Divi - Added to the wiki page.
