### ISSUE TITLE
Chunk decrypt

### ISSUE THREAD

**Issue by demplays** [loldevs/leaguespec#29]
Hi, first of all great work on spectator related documentation. 

I was wondering how advanced is chunk decryption going since your site Riftwalk seems to use it to get the stats in real time.
I'm currently developing an application (almost completed) to record and play games and would be great to decrypt in real time. I also have some experience of riot's data flux and implementation so fell free to ask questions.

**Comment by jaagupkymmel** [comment]
From what I know, chunks are basicly dump of packets, so it shouldn't be too hard to figure out.

**Comment by demplays** [comment]
Is there any structure defined yet besides https://gist.github.com/jaagupkymmel/8939b876dd164b71ad9f ?

**Comment by jaagupkymmel** [comment]
I'm not sure that these bitflags apply to chunks.

**Comment by honux** [comment]
Won't quote, but someone confirmed that they do apply.

**Comment by demplays** [comment]
Well my main objective is to get kills (assists, positions, champions) from the spectator chunks. Or is it possible to get them from keyframes? I mean instant kills not stats every 60 seconds

**Comment by Divi** [comment]
KDA are easy to find, just compare positions with the official Riot timeline data.

**Comment by demplays** [comment]
will do, thanks
