### ISSUE TITLE
Discussion: Open or Closed

### ISSUE THREAD

**Issue by themasch** [loldevs/leaguespec#3]
> @jaagupkymmel  (on [issue#1 lol-ob](https://github.com/robertabcd/lol-ob/issues/1#issuecomment-34305730))
> May I suggest making the wiki private, atleast for the time being. I'm fairly certain none  of us want this information to get in hands of people who might use it to create malicious content and I don't think Riot would be too happy to see that someone can read all their spectator data, especially if they share it publicly.
> 
> We should still give everyone who wishes to contribute access to it

Please discuss this. 

Votings done: 
**close**  (@jaagupkymmel)
**open** (@lukegb)
**open** (@themasch)
**open** (@tyscorp)
**open** (@Divi)

**Comment by tyscorp** [comment]
I'm for keeping it open source. It's not like Riot could actually shut us down. Sure, they could ask us to stop and get the repo removed or whatever, but we would still already have the knowledge.

Having said that, I would still probably comply with a C&D from Riot.

**Comment by lukegb** [comment]
If we actually got a C&D from Riot we could probably just go underground if we really wanted to keep going.

Also, making the wiki private is effort and costs money.

**Comment by Divi** [comment]
Even if we turn this project to closed-source, everybody will be able to access to our project by asking it. Riot included.
I just don't feel comfortable with cheaters/hackers who can use these data to learn the live game decryption workflow.

The project is developed by the community, not just by one or two people, so let it open-source.
Btw, keep a mirror of this project may be useful.

**Comment by jaagupkymmel** [comment]
It seems we are keeping it open-source.
