### ISSUE TITLE
How to get the game id of the current game?

### ISSUE THREAD

**Issue by NitroXenon** [loldevs/leaguespec#32]
I'm going to make a replay tool for Korean and Taiwan client. How can I get the game id and the ecryption key of the current game?

**Comment by strangeglyph** [comment]
You need an RTMP call to
gameService.retrieveInProgressSpectatorGameInfo(String summoner).
That's how it works on most regions anyway. Garena might be doing
their own thing as usual.

**Comment by NitroXenon** [comment]
lol but how can I do it in C#??

**Comment by strangeglyph** [comment]
Either look for an RTMP library written in C# or write your own.
Existing libs:
- [Astralfoxy's RTMPsharp](https://github.com/astralfoxy/rtmp-sharp)

If you decide to roll your own, here's some docs to get you started:
- [AMF 1.0 spec](https://a248.e.akamai.net/f/1953/8974/2h/wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/devnet/amf/pdf/amf-file-format-spec.pdf)
- [AMF 3.0 spec](https://a248.e.akamai.net/f/1953/8974/2h/wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/devnet/amf/pdf/amf-file-format-spec.pdf)
- [RTMP spec](https://www.adobe.com/content/dam/Adobe/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf)

**Comment by NitroXenon** [comment]
Is it need to login using the LoL account first?

**Comment by strangeglyph** [comment]
Yes. You need to get through the login queue to get an auth token, and use that token to log into the rtmp servers

**Comment by NitroXenon** [comment]
Oh I see. Thanks~

**Comment by NitroXenon** [comment]
But there is another problem. I can't login to TW server using RTMP so I can't get any data.

Can I use a UdpClient to track the RTMP messages send form the server and the client? Is it work?

**Comment by eddy5641** [comment]
You have to connect with partner credentials, an illogical thing that garena requires for you to login.
