### ISSUE TITLE
Map Mastery IDs in Keyframes to masteryId in AIR Client

### ISSUE THREAD

**Issue by tyscorp** [loldevs/leaguespec#4]
The ones in the keyframes are completely different, ranging from like 40 to 100 or something.

The AIR mastery data can be found [here](http://ddragon.leagueoflegends.com/cdn/4.1.2/data/en_US/mastery.json).

Edit: I'd rather not do this. Someone looking for a way to help out, feel free!

**Comment by jaagupkymmel** [comment]
http://pastebin.com/4FYD0yrJ
