### ISSUE TITLE
Question about hex decoding

### ISSUE THREAD

**Issue by Divi** [loldevs/leaguespec#6]
Hello,

I'm not familiar with the hex to decimal process. I know how to obtain a string or int value, but for a float, i'm a little bit lost.

For example, in the keyframe spec, on this unknown data bloc (https://github.com/loldevs/leaguespec/wiki/Keyframe-Specification#wiki-unknown-data-3) there are some float values, but I just don't know how you can get these values.

So if someone can explain to me, it would be great !

Thanks :)

**Comment by tyscorp** [comment]
You either do it programmatically with a function like "readFloatLE" (or pack/unpack in some scripting languages like ruby/php) or just use a [website](http://gregstoll.dyndns.org/~gregstoll/floattohex/) to do it.

Remember to put it in reverse byte order if using a website. (e.g. 93 85 30 43 -> 0x43308593)

**Comment by Divi** [comment]
Thanks @tyscorp, this is why I can't find the right value with my calculator :(
Last question : how can you find the right value type (int, float, string, etc) ? We have to guess it ?

**Comment by tyscorp** [comment]
Yep. I just copy+paste a portion of data into my text editor and add spaces/newlines at different points until patterns emerge and it starts to make sense. If I see XX 00 00 00 or XX XX 00 00 I usually think it's an int. If it's like groups of 4 quite different values with the last (first, I guess) byte being a 4X you can assume it's a float.

**Comment by Zykloide** [comment]
By the way the line "Note: everything is in little endian." in https://github.com/loldevs/leaguespec/wiki/Keyframe-Specification#wiki-general-structure tells you that it's stored in reversed order. For more information: http://en.wikipedia.org/wiki/Endianness :)

**Comment by Divi** [comment]
Thanks :)
