### ISSUE TITLE
Changes in chatroom name generation

### ISSUE THREAD

**Issue by jaagupkymmel** [loldevs/leaguespec#9]
As some of you might know, Riot moved invitation process from XMPP to RTMP with the new patch. I recieved an email asking whether or not the party/game lobby chatroom name generation got changed aswell with that patch?

**Comment by snowl** [comment]
I'll check into this - I'm fairly sure it's changed a bit. Looks like it's based on a "chatKey" now.

**Comment by horato** [comment]
it looks like this "chatKey": "AXFdWPHVlr" :)

**Comment by Divi** [comment]
In the RTMP API, there is a key called "roomPassword" or "roomKey" if I remember, with value like your "AXFdWPHVlr".

**Comment by horato** [comment]
anything new on this?

**Comment by btastic** [comment]
he edited the wiki entry just yesterday:

"For example, with the chatKey h0HrnkNvAm and invitationId INVID2137627, the room would be ag~96f56bc2e656062772f07b676e6e890c9bf5ed20@sec.pvp.net"

I'm really looking forward for more research onto this. Does somebody know how to reverse parts of the lolclient? I feel like I want to help :)

**Comment by horato** [comment]
Nice, we have some progress at least ^^
https://tuts4you.com/download.php?view.2876 Try this thing. It might be usefull for you.

**Comment by eddy5641** [comment]
Using a SHA1 decrypter and inputting in:
"96f56bc2e656062772f07b676e6e890c9bf5ed20"
Gives this:
invid2137627

**Comment by eddy5641** [comment]
Looked into it, INVID2137627 is changed to invid2137627 and hashed with the SHA1
This outputs "96f56bc2e656062772f07b676e6e890c9bf5ed20" and the prefix "ag~" and the sufix "@sec.pvp.net" is attached. The chatKey is the password to join the room.
